import React from 'react';
import {
  SettingOutlined,
  UserOutlined,
  TeamOutlined,
  FileOutlined,
  ToolOutlined,
  PieChartOutlined,
  AppstoreOutlined,
  TableOutlined,
  LockOutlined,
  SafetyOutlined,
  MenuOutlined,
  DashboardOutlined,
  ProfileOutlined,
  CodeOutlined,
  DatabaseOutlined,
  CloudOutlined,
  BellOutlined,
  MailOutlined,
  MessageOutlined,
  FormOutlined,
  UnorderedListOutlined,
  BarChartOutlined,
  LineChartOutlined,
  FundOutlined,
  LinkOutlined,
  GlobalOutlined,
  HomeOutlined,
  ShopOutlined,
  MonitorOutlined,
  BugOutlined,
  ApiOutlined,
  BookOutlined,
  ReadOutlined,
  EditOutlined,
  SolutionOutlined,
  HddOutlined,
} from '@ant-design/icons';

const iconMap: Record<string, React.ReactNode> = {
  setting: <SettingOutlined />,
  user: <UserOutlined />,
  peoples: <TeamOutlined />,
  'tree-table': <TableOutlined />,
  tool: <ToolOutlined />,
  dashboard: <DashboardOutlined />,
  chart: <PieChartOutlined />,
  guide: <AppstoreOutlined />,
  lock: <LockOutlined />,
  safety: <SafetyOutlined />,
  menu: <MenuOutlined />,
  profile: <ProfileOutlined />,
  code: <CodeOutlined />,
  database: <DatabaseOutlined />,
  cloud: <CloudOutlined />,
  bell: <BellOutlined />,
  mail: <MailOutlined />,
  message: <MessageOutlined />,
  form: <FormOutlined />,
  list: <UnorderedListOutlined />,
  'bar-chart': <BarChartOutlined />,
  'line-chart': <LineChartOutlined />,
  fund: <FundOutlined />,
  link: <LinkOutlined />,
  global: <GlobalOutlined />,
  home: <HomeOutlined />,
  shop: <ShopOutlined />,
  monitor: <MonitorOutlined />,
  bug: <BugOutlined />,
  api: <ApiOutlined />,
  file: <FileOutlined />,
  table: <TableOutlined />,
  system: <SettingOutlined />,
  dict: <BookOutlined />,
  log: <ReadOutlined />,
  online: <TeamOutlined />,
  edit: <EditOutlined />,
  redis: <HddOutlined />,
  post: <SolutionOutlined />,
};

export function getIcon(name?: string): React.ReactNode | undefined {
  if (!name) return undefined;
  return iconMap[name] || <AppstoreOutlined />;
}

/** All available icon options for menu form select */
export const iconOptions = Object.keys(iconMap).map((key) => ({
  label: key,
  value: key,
  icon: iconMap[key],
}));
